model_list:
- litellm_params:
    api_base: http://modeldeployment-meta-llama-3-1-8b-instruct-dgx-spark.nemo-microservices.svc.cluster.local:8000/v1
    api_key: none
    model: openai/meta/llama-3.1-8b-instruct-dgx-spark
  model_name: meta/llama-3.1-8b-instruct-dgx-spark
