apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: miramar-gateway
  namespace: model-router
  annotations:
    networking.gke.io/pre-shared-certs: miramar-api-cert
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
  addresses:
    - type: NamedAddress
      value: miramar-gateway-ip
