set -g status-interval 5
set -g status-left-length 80
set -g status-right-length 200

set -g message-style "bg=colour22,fg=colour231"
set -g pane-border-style "fg=colour34"
set -g pane-active-border-style "fg=colour46"

set -g status-left '#[fg=colour16,bg=colour46,bold] #H #[fg=colour16,bg=colour46]| #[fg=colour16,bg=colour46,bold] #S#{?client_prefix, PREFIX,} '

set -g status-style "bg=colour46,fg=colour16"

set -g status-right '#[fg=colour16,bg=colour46] #(~/bin/tmux-status ai) #[fg=colour16,bg=colour46]| #(~/bin/tmux-status ip) '

setw -g window-status-format '#[fg=colour16,bg=colour46] #I:#(~/bin/tmux-status app "#{pane_tty}") '
setw -g window-status-current-format '#[fg=colour16,bg=colour40,bold] #I:#(~/bin/tmux-status app "#{pane_tty}") '
