# Generated by notebook.ipynb — do not edit manually.
# Re-run the Build → pipeline.py cell in notebook.ipynb to regenerate.

from kfp import dsl
from kfp.dsl import Input, Output, Dataset, Model, Artifact


@dsl.component(base_image="python:3.11-slim")
def step_1(output_data: Output[Dataset]):
    import pathlib
    pathlib.Path(output_data.path).write_text("placeholder")
    print("step_1 done")


@dsl.pipeline(name="{{PROJECT_NAME}}")
def pipeline():
    step_1()
